# Generated by Django 6.1 on 2026-09-27 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Género",
                "verbose_name_plural": "Géneros",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Resena",
            fields=[
                ("id_resena", models.AutoField(primary_key=True, serialize=False)),
                ("texto", models.TextField()),
                ("calificacion", models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                "verbose_name": "Reseña",
                "verbose_name_plural": "Reseñas",
            },
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("nacionalidad", models.CharField(max_length=100)),
                ("anio_de_nacimiento", models.DateField()),
            ],
            options={
                "verbose_name": "Actor",
                "verbose_name_plural": "Actores",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "nombre",
                            "apellido",
                            "nacionalidad",
                            "anio_de_nacimiento",
                        ),
                        name="actor_unico",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("nacionalidad", models.CharField(max_length=100)),
                ("anio_de_nacimiento", models.DateField()),
            ],
            options={
                "verbose_name": "Director",
                "verbose_name_plural": "Directores",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "nombre",
                            "apellido",
                            "nacionalidad",
                            "anio_de_nacimiento",
                        ),
                        name="director_unico",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("sinopsis", models.TextField()),
                ("duracion_minutos", models.PositiveIntegerField()),
                ("fecha_estreno", models.DateField()),
                ("url_trailer", models.URLField(blank=True)),
                (
                    "clasificacion",
                    models.CharField(
                        choices=[
                            ("ATP", "Apta para todo público"),
                            ("M13", "Apta para mayores de 13 años"),
                            ("M16", "Apta para mayores de 16 años"),
                            ("M18", "Apta para mayores de 18 años"),
                        ],
                        default="ATP",
                        max_length=5,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "imagen_portada",
                    models.ImageField(
                        upload_to="peliculas/posters/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                    ),
                ),
                (
                    "calificacion_promedio",
                    models.DecimalField(decimal_places=1, default=0.1, max_digits=3),
                ),
                (
                    "actores",
                    models.ManyToManyField(
                        related_name="peliculas", to="peliculas.actor"
                    ),
                ),
                (
                    "directores",
                    models.ManyToManyField(
                        related_name="peliculas", to="peliculas.director"
                    ),
                ),
                (
                    "generos",
                    models.ManyToManyField(
                        blank=True, related_name="peliculas", to="peliculas.genero"
                    ),
                ),
            ],
            options={
                "verbose_name": "Película",
                "verbose_name_plural": "Películas",
                "ordering": ["-fecha_estreno", "titulo"],
            },
        ),
    ]
