# Generated by Django 6.1 on 2026-09-14 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nombre", "apellido"), name="actor_unico"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nombre", "apellido"), name="director_unico"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("sinopsis", models.TextField()),
                ("duracion_minutos", models.PositiveIntegerField()),
                ("fecha_estreno", models.DateField()),
                ("url_trailer", models.URLField(blank=True)),
                (
                    "clasificacion",
                    models.CharField(
                        choices=[
                            ("ATP", "Apta para todo público"),
                            ("M13", "Apta para mayores de 13 años"),
                            ("M16", "Apta para mayores de 16 años"),
                            ("M18", "Apta para mayores de 18 años"),
                        ],
                        max_length=5,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "imagen_portada",
                    models.ImageField(
                        upload_to="peliculas/posters/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                    ),
                ),
                ("calificacion", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "actores",
                    models.ManyToManyField(
                        related_name="peliculas", to="peliculas.actor"
                    ),
                ),
                (
                    "directores",
                    models.ManyToManyField(
                        related_name="peliculas", to="peliculas.director"
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_estreno", "titulo"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("titulo", "fecha_estreno"),
                        name="pelicula_unica_por_titulo_y_fecha",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("titulo", ""), _negated=True),
                        name="pelicula_titulo_no_vacio",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sinopsis", ""), _negated=True),
                        name="pelicula_sinopsis_no_vacia",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("duracion_minutos__gt", 0)),
                        name="pelicula_duracion_positiva",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("fecha_estreno__gte", "1888-01-01")),
                        name="pelicula_fecha_estreno_valida",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("calificacion__gte", 0.1), ("calificacion__lte", 10)
                        ),
                        name="pelicula_calificacion_en_rango",
                    ),
                ],
            },
        ),
    ]
