# Generated by Django 6.1 on 2026-09-27 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("peliculas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resena",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resenas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resena",
            name="pelicula",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resenas",
                to="peliculas.pelicula",
            ),
        ),
        migrations.AddIndex(
            model_name="pelicula",
            index=models.Index(
                fields=["-fecha_estreno"], name="idx_pelicula_fecha_estreno"
            ),
        ),
        migrations.AddIndex(
            model_name="pelicula",
            index=models.Index(
                fields=["-calificacion_promedio"], name="idx_pelicula_calif_desc"
            ),
        ),
        migrations.AddConstraint(
            model_name="pelicula",
            constraint=models.UniqueConstraint(
                fields=("titulo", "fecha_estreno"),
                name="pelicula_unica_por_titulo_y_fecha",
            ),
        ),
        migrations.AddConstraint(
            model_name="pelicula",
            constraint=models.CheckConstraint(
                condition=models.Q(("titulo", ""), _negated=True),
                name="pelicula_titulo_no_vacio",
            ),
        ),
        migrations.AddConstraint(
            model_name="pelicula",
            constraint=models.CheckConstraint(
                condition=models.Q(("sinopsis", ""), _negated=True),
                name="pelicula_sinopsis_no_vacia",
            ),
        ),
        migrations.AddConstraint(
            model_name="pelicula",
            constraint=models.CheckConstraint(
                condition=models.Q(("duracion_minutos__gt", 0)),
                name="pelicula_duracion_positiva",
            ),
        ),
        migrations.AddConstraint(
            model_name="pelicula",
            constraint=models.CheckConstraint(
                condition=models.Q(("fecha_estreno__gte", "1888-01-01")),
                name="pelicula_fecha_estreno_valida",
            ),
        ),
        migrations.AddConstraint(
            model_name="pelicula",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("calificacion_promedio__gte", 0.1),
                    ("calificacion_promedio__lte", 10),
                ),
                name="pelicula_calificacion_en_rango",
            ),
        ),
        migrations.AddConstraint(
            model_name="resena",
            constraint=models.UniqueConstraint(
                fields=("pelicula", "autor"), name="unica_reseña_por_usuario_y_pelicula"
            ),
        ),
        migrations.AddConstraint(
            model_name="resena",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("calificacion__gte", 0.1), ("calificacion__lte", 10.0)
                ),
                name="resena_calificacion_en_rango",
            ),
        ),
    ]
