# Generated by Django 6.1 on 2026-09-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peliculas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="edad",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
