# Generated by Django 6.1 on 2026-09-15 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peliculas", "0002_actor_edad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resena",
            fields=[
                ("id_resena", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_usuario", models.CharField(max_length=100)),
                ("texto", models.TextField()),
                ("calificacion", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "pelicula_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resenas",
                        to="peliculas.pelicula",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pelicula_id", "nombre_usuario"),
                        name="unica_reseña_por_usuario_y_pelicula",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("calificacion__gte", 0.1), ("calificacion__lte", 10.0)
                        ),
                        name="resena_calificacion_en_rango",
                    ),
                ],
            },
        ),
    ]
