# Generated by Django 6.1 on 2026-09-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peliculas", "0003_resena"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pelicula",
            name="calificacion",
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=3),
        ),
        migrations.AlterField(
            model_name="pelicula",
            name="clasificacion",
            field=models.CharField(
                choices=[
                    ("ATP", "Apta para todo público"),
                    ("M13", "Apta para mayores de 13 años"),
                    ("M16", "Apta para mayores de 16 años"),
                    ("M18", "Apta para mayores de 18 años"),
                ],
                default="ATP",
                max_length=5,
            ),
        ),
    ]
