# Generated by Django 6.1 on 2026-09-24 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peliculas", "0004_alter_pelicula_calificacion_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="actor",
            name="actor_unico",
        ),
        migrations.RemoveConstraint(
            model_name="director",
            name="director_unico",
        ),
        migrations.AddField(
            model_name="actor",
            name="anio_de_nacimiento",
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="actor",
            name="nacionalidad",
            field=models.CharField(default="Argentina", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="director",
            name="anio_de_nacimiento",
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="director",
            name="nacionalidad",
            field=models.CharField(default="Argentina", max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="actor",
            constraint=models.UniqueConstraint(
                fields=("nombre", "apellido", "nacionalidad", "anio_de_nacimiento"),
                name="actor_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="director",
            constraint=models.UniqueConstraint(
                fields=("nombre", "apellido", "nacionalidad", "anio_de_nacimiento"),
                name="director_unico",
            ),
        ),
        migrations.RemoveField(
            model_name="actor",
            name="edad",
        ),
    ]
