# Generated by Django 6.1 on 2026-09-24 22:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peliculas", "0005_remove_actor_actor_unico_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto_de_perfil",
                    models.ImageField(
                        blank=True,
                        upload_to="static/peliculas/recursos/imagenes/perfiles/fotos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                    ),
                ),
                ("biografia", models.TextField(blank=True)),
                ("generos_favoritos", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="pelicula",
            name="pelicula_calificacion_en_rango",
        ),
        migrations.RemoveConstraint(
            model_name="resena",
            name="unica_reseña_por_usuario_y_pelicula",
        ),
        migrations.RenameField(
            model_name="pelicula",
            old_name="calificacion",
            new_name="calificacion_promedio",
        ),
        migrations.AddField(
            model_name="resena",
            name="autor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resenas",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="pelicula",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("calificacion_promedio__gte", 0.1),
                    ("calificacion_promedio__lte", 10),
                ),
                name="pelicula_calificacion_en_rango",
            ),
        ),
        migrations.AddConstraint(
            model_name="resena",
            constraint=models.UniqueConstraint(
                fields=("pelicula_id", "autor"),
                name="unica_reseña_por_usuario_y_pelicula",
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="resena",
            name="nombre_usuario",
        ),
    ]
