# Generated by Django 6.1 on 2026-09-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peliculas", "0006_perfil_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="pelicula",
            name="generos",
            field=models.ManyToManyField(
                blank=True, related_name="peliculas", to="peliculas.genero"
            ),
        ),
    ]
