# Generated by Django 6.1 on 2026-09-25 04:16

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peliculas", "0007_genero_pelicula_generos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="resena",
            name="unica_reseña_por_usuario_y_pelicula",
        ),
        migrations.RenameField(
            model_name="resena",
            old_name="pelicula_id",
            new_name="pelicula",
        ),
        migrations.AlterField(
            model_name="perfil",
            name="foto_de_perfil",
            field=models.ImageField(
                blank=True,
                upload_to="perfiles/fotos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="pelicula",
            index=models.Index(
                fields=["-fecha_estreno"], name="idx_pelicula_fecha_estreno"
            ),
        ),
        migrations.AddIndex(
            model_name="pelicula",
            index=models.Index(
                fields=["-calificacion_promedio"], name="idx_pelicula_calif_desc"
            ),
        ),
        migrations.AddConstraint(
            model_name="resena",
            constraint=models.UniqueConstraint(
                fields=("pelicula", "autor"), name="unica_reseña_por_usuario_y_pelicula"
            ),
        ),
    ]
