# Generated by Django 6.1 on 2026-09-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "peliculas",
            "0008_remove_resena_unica_reseña_por_usuario_y_pelicula_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={"verbose_name": "Actor", "verbose_name_plural": "Actores"},
        ),
        migrations.AlterModelOptions(
            name="director",
            options={"verbose_name": "Director", "verbose_name_plural": "Directores"},
        ),
        migrations.AlterModelOptions(
            name="genero",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Género",
                "verbose_name_plural": "Géneros",
            },
        ),
        migrations.AlterModelOptions(
            name="pelicula",
            options={
                "ordering": ["-fecha_estreno", "titulo"],
                "verbose_name": "Película",
                "verbose_name_plural": "Películas",
            },
        ),
        migrations.AlterModelOptions(
            name="perfil",
            options={"verbose_name": "Perfil", "verbose_name_plural": "Perfiles"},
        ),
        migrations.AlterModelOptions(
            name="resena",
            options={"verbose_name": "Reseña", "verbose_name_plural": "Reseñas"},
        ),
    ]
